dw_processed_claim_from_dw_claim = {
    "account": '"domain"',
    "amt_paid_to_pharmacy": "client_employer_cost",
    "auth_id": "CAST (auth_id as int)",
    "basis_of_cost_determination": "request_basis_of_cost_determination",
    "benefit_plan_name": "benefit_plan_name",
    "bin": "request_bin_number",
    "calculated_disp_fee": "calculated_disp_fee",
    "calculated_gross_due": "calculated_employer_cost",
    "calculated_ing_cost": "calculated_ing_cost",
    "calculated_sales_tax": "response_flat_sales_tax_amount_paid",
    "carrier": "'FLIPT' as flipt",
    "claim_date": """TO_DATE(
        TO_DATE(request_date_of_service,'YYYYmmDD')
        ,'YYYY-MM-DDT00:00:00.000000')""",
    "claim_override_flag": "over_ride",
    "claim_status": "claim_status",
    "claim_type": "request_transaction_code",
    "client_copay": "client_employee_paid",
    "client_deductible": "client_deductible",
    "client_disp_fee": "client_disp_fee_paid",
    "client_due_amt": "client_employer_cost",
    "client_employee_paid": "client_employee_paid",
    "client_ing_cost": "client_ing_cost",
    "client_paid_amt": "client_employer_cost",
    "client_sales_tax": "client_plan_sales_tax_amount_paid",
    "compound_drug_flag": "request_compound_code",
    "compound_ind": "request_compound_code",
    "date_of_prescription": "request_date_prescription_written",
    "date_of_service": """TO_DATE(
        TO_DATE(request_date_of_service,'YYYYmmDD')
        ,'YYYY-MM-DDT00:00:00.000000')""",
    "daw_code": "request_product_selection_code",
    "days_supply": "request_days_supply",
    "deductible_accumulator_flag": "deductible_accumulator_flag",
    "disp_fee_paid": "client_disp_fee_paid",
    "drug_name": "drug_name",
    "drug_strength": "drug_strength",
    "enddate": "endDate",
    "erx_transaction_id": "transactionId",
    "fill_date": """TO_DATE(
        TO_DATE(request_date_of_service,'YYYYmmDD')
        ,'YYYY-MM-DDT00:00:00.000000')""",
    "fill_number": "request_fill_number",
    "flipt_auth_id": "auth_id",
    "flipt_person_code": "RIGHT(request_cardholder_id,2)",
    "flipt_rel_code": "RIGHT(request_cardholder_id,2)",
    "generic_brand_ind": "brand_generic",
    "gpi_code": "request_gpi",
    '"group"': "request_group_id",
    "ing_cost_paid": "client_ing_cost",
    "load_date": "CURRENT_DATE",
    "manuf_abr": "drug_manufacturer",
    "member_id": "request_cardholder_id",
    "member_relationship": "request_person_code",
    "multisource_code": "multi_source",
    "oop_accumulator_flag": "oop_accumulator_flag",
    "otc_indicator": "otc_indicator",
    "other_coverage_code": "request_other_coverage_code",
    "pack_size": "package_size",
    "patient_paid": "client_employee_paid",
    "payer_auth_id": "payer_authid",
    "payer_name": "claims_processor",
    "pcn": "request_processor_control_number",
    "person_code": "request_person_code",
    "pharmacy_chain": "pharmacy_chain_code",
    "pharmacy_name": "pharmacy_name",
    "pharmacy_npi": "request_service_provider_id",
    "preganancy_indicator": "request_pregnancy_indicator",
    "prescriber_first_name": "request_prescriber_first_name",
    "prescriber_last_name": "request_prescriber_last_name",
    "prescriber_npi": "request_prescriber_id",
    "prescription_origin_code": "request_prescription_origin_code",
    "product_id_ndc": "request_product_id",
    "product_name_full": "drug_name",
    "payee_type": "payee_type",
    "quantity_dispensed": "request_quantity_dispensed",
    "rel_code": "request_person_code",
    "response_disc_fee": "client_disp_fee_paid",
    "response_gross_due": "response_total_amount_paid",
    "response_ing_cost": "client_ing_cost",
    "response_sales_tax": "response_flat_sales_tax_amount_paid",
    "rx_alternate_drug_reward": "alternative_drug_rewards",
    "rx_alternate_penalty": "alternate_penalty",
    "rx_dispensing_fee": "pharmacy_dispensing_fee",
    "rx_domain": '"domain"',
    "rx_drug_cost": "calculated_drug_cost",
    "rx_employee_opc": "employee_opc",
    "rx_employer_cost": "calculated_employer_cost",
    "rx_number": "request_prescription_reference_number",
    "rx_pa_flag": "pa_flag",
    "rx_penalty": "drug_penalty",
    "rx_prescription_id": "prescription_id",
    "rx_quantity": "request_quantity_dispensed",
    "rx_rebate_amount": "rebate_amount",
    "rx_rebate_factor": "rebate_factor",
    "rx_rewards": "rewards",
    "rx_unit_price": "unit_price",
    "rx_unit_price_before_rebate": "unit_price_before_rebate",
    "sales_tax_paid": "response_flat_sales_tax_amount_paid",
    "startdate": "startdate",
    '"status"': "claim_status",
    "submission_clarification_code": "request_submission_clarification_code",
    "submission_clarification_count": "request_submission_clarification_code_count",
    "submitted_date": "request_date_of_service",
    "submitted_disp_fee": "request_dispensing_fee_submitted",
    "submitted_dispensing_fee": "request_dispensing_fee_submitted",
    "submitted_gross_due": "submitted_drug_cost",
    "submitted_ing_cost": "submitted_ing_cost",
    "submitted_sales_tax": "request_percentage_sales_tax_amount_submitted",
    "submitted_time": "startdate",
    "submitted_uc": "unc_drug_cost",
    "submitted_usual_and_customary_ams": "unc_drug_cost",
    "total_amount_paid": "client_employer_cost",
    "transfer_bin": "transferrequest_bin_number",
    "transfer_pcn": "transferrequest_processor_control_number",
    "written_date": "request_date_prescription_written",
    "submitted_total_amount": "submitted_drug_cost",
    "total_reward": "total_reward",
    "rx_flipt_person_id": "rx_flipt_person_id",
    "sequence_number": "sequencenumber",
    "payer_patient_paid_amount": "payer_patient_paid_amount",
    "payer_ing_cost": "payer_ing_cost",
    "payer_dispensing_fee": "payer_dispensing_fee",
    "payer_sales_tax": "payer_sales_tax",
    "oop_accumulator_amount": "oop_accumulator_amount",
    "deductible_accumulator_amount": "deductible_accumulator_amount",
    "awp_amount": "awp_amount",
    "awp_unit_price": "awp_unit_price",
    "admin_fee": "admin_fee",
    "mail_retail_code": "mail_retail_code",
    "pharmacy_type": "pharmacy_type",
    "employee_id": "employee_id",
    "retail_reward": "retail_reward",
    "specialty_flag": "specialty_flag",
    "member_choice_penalty_amount": "member_choice_penalty_amount",
    "payer_sequence_number": "payer_sequence_number",
    "client_patient_sales_tax_amount_paid": "client_patient_sales_tax_amount_paid",
    "number_of_refills_authorized": "request_number_of_refills_authorized",
    "incentive_credit_applied": "incentive_credit_applied",
    "incentive_credit_remaining": "incentive_credit_remaining",
    "rds_subsidy_determination_indicator": "rds_subsidy_determination_indicator",
    "medicare_type": "medicare_type"
}

insert_processed_claims_sql = """
    INSERT INTO flipt_dw.dw_processedclaims
    ({dest_cols})
    SELECT {select_vals}
    FROM flipt_dw.dw_claims
    WHERE transactionId NOT IN (SELECT erx_transaction_id FROM flipt_dw.dw_processedclaims \
        where erx_transaction_id is not Null)
    AND claim_status in ('P', 'X') AND process_error_code is null
""".format(
    dest_cols=",".join(dw_processed_claim_from_dw_claim.keys()),
    select_vals=",".join(dw_processed_claim_from_dw_claim.values()),
)
